services:
  mysql-1:
    image: mysql:latest
    container_name: mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ordersdb
      TZ: Asia/Seoul
    ports:
      - 3306:3306

  mysql-2:
    image: mysql:latest
    container_name: mysql-2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: paymentsdb
      TZ: Asia/Seoul
    ports:
      - 3307:3306

  mysql-3:
    image: mysql:latest
    container_name: mysql-3
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: stockdb
      TZ: Asia/Seoul
    ports:
      - 3308:3306      
          
  mysql-4:
    image: mysql:latest
    container_name: mysql-4
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: deliverydb
      TZ: Asia/Seoul
    ports:
      - 3309:3306  

  kafka-1:
    image: apache/kafka:3.7.0
    container_name: kafka-1
    ports:
      - 9092:9092
